import { getAssetFromKV } from '@cloudflare/kv-asset-handler';

// The manifest is generated by Wrangler and contains a map of file paths to their content hashes.
import manifestJSON from '__STATIC_CONTENT_MANIFEST';
const assetManifest = JSON.parse(manifestJSON);

export default {
  async fetch(request, env, ctx) {
    try {
      return await getAssetFromKV(
        {
          request,
          waitUntil(promise) {
            return ctx.waitUntil(promise);
          },
        },
        {
          ASSET_NAMESPACE: env.__STATIC_CONTENT,
          ASSET_MANIFEST: assetManifest,
        }
      );
    } catch (e) {
      // Fallback for 404 - return the index.html content
      try {
        let notFoundResponse = await getAssetFromKV({
          request,
          waitUntil(promise) {
            return ctx.waitUntil(promise);
          },
        }, {
          ASSET_NAMESPACE: env.__STATIC_CONTENT,
          ASSET_MANIFEST: assetManifest,
          mapRequestToAsset: req => new Request(`${new URL(req.url).origin}/index.html`, req),
        });

        return new Response(notFoundResponse.body, { ...notFoundResponse, status: 404 });
      } catch (e) {
        return new Response(e.message || e.toString(), { status: 500 });
      }
    }
  },
};
